/**
 * Engine — reads CONFIG, loads components, renders & animates.
 * DO NOT edit this file for customization. Edit config.js only.
 */

// ── Theme ────────────────────────────────────────────────────────
let currentMode = "light";

function applyTheme(mode) {
  currentMode = mode;
  const root = document.documentElement;
  const c = CONFIG.colors;

  root.style.setProperty("--primary", c.primary || "#ff69b4");
  root.style.setProperty("--accent", c.accent || "#15a1ed");

  const theme = c[mode] || c.light || {};
  root.style.setProperty("--bg", theme.background || "#fafaf9");
  root.style.setProperty("--text", theme.text || "#1e293b");
}

// ── Script Loader ────────────────────────────────────────────────
function loadScript(src) {
  return new Promise((resolve, reject) => {
    const s = document.createElement("script");
    s.src = src;
    s.onload = resolve;
    s.onerror = () => reject(new Error("Component not found: " + src));
    document.head.appendChild(s);
  });
}

// ── Main ─────────────────────────────────────────────────────────
document.addEventListener("DOMContentLoaded", async () => {
  applyTheme(currentMode);

  // Set music source & auto-play
  const audio = document.querySelector(".song");
  if (audio && CONFIG.music) {
    audio.querySelector("source").src = CONFIG.music;
    audio.load();
    audio.play().catch(() => {});
  }

  // Determine unique component types
  const types = [...new Set(CONFIG.sections.map((s) => s.type))];

  // Dynamically load component scripts
  for (const type of types) {
    try {
      await loadScript(`./script/components/${type}.js`);
    } catch (e) {
      console.warn(e.message);
    }
  }

  // Render all sections
  const container = document.querySelector(".container");
  const rendered = [];

  CONFIG.sections.forEach((section) => {
    const comp = window.Components && window.Components[section.type];
    if (!comp) {
      console.warn(`Component "${section.type}" not found, skipping.`);
      return;
    }
    const el = comp.render(container, section, CONFIG);
    rendered.push({ el, comp, section });
  });

  // Create Start button
  const startBtn = document.createElement("button");
  startBtn.id = "start-btn";
  startBtn.textContent = "Start";
  startBtn.style.cssText = `
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    padding: 15px 40px;
    font-size: 1.2rem;
    background: linear-gradient(135deg, var(--primary), var(--accent));
    color: white;
    border: none;
    border-radius: 50px;
    cursor: pointer;
    z-index: 9998;
    box-shadow: 0 4px 15px rgba(0,0,0,0.3);
    font-family: 'Poppins', sans-serif;
    font-weight: 600;
    transition: transform 0.2s;
  `;
  startBtn.addEventListener("mouseover", () => startBtn.style.transform = "translate(-50%, -50%) scale(1.05)");
  startBtn.addEventListener("mouseout", () => startBtn.style.transform = "translate(-50%, -50%)");
  startBtn.addEventListener("click", () => {
    startBtn.remove();
    if (audio) audio.play().catch(() => {});
    buildTimeline(rendered);
  });
  document.body.appendChild(startBtn);
});

// ── Timeline Builder ─────────────────────────────────────────────
function buildTimeline(rendered) {
  const tl = gsap.timeline();

  tl.to(".container", { duration: 0.6, visibility: "visible" });

  // Track deferred exits for overlay components
  let deferredExits = [];

  rendered.forEach(({ el, comp, section }, i) => {
    const isOverlay = comp.overlay === true;

    // Flush deferred exits before non-overlay sections
    if (!isOverlay && deferredExits.length > 0) {
      deferredExits.forEach((fn) => fn());
      deferredExits = [];
    }

    // Animate
    comp.animate(tl, el, CONFIG);

    // Handle exit lifecycle
    if (comp.exit) {
      const next = rendered[i + 1];
      const nextIsOverlay = next && next.comp.overlay === true;

      if (nextIsOverlay) {
        deferredExits.push(() => comp.exit(tl, el));
      } else if (!isOverlay) {
        comp.exit(tl, el);
      }
    }
  });

  // Flush remaining
  deferredExits.forEach((fn) => fn());

  // Setup replay
  const replayBtn = document.getElementById("replay");
  if (replayBtn) {
    replayBtn.addEventListener("click", () => tl.restart());
  }
}
